### ISSUE TITLE
When a secret door is open, the door is still opaque

### ISSUE THREAD

**Issue by ExDomino** [Wyn-Price/SecretRooms#10]
Hello,

When a door is open, the visual of the door is still opaque, like if it's closed.
I don't know if the problem is only client-side or not.

Version: 1.12.2-5.6.4.

**Comment by Wyn-Price** [comment]
Could you send a photo of the issue

**Comment by ExDomino** [comment]
When closed: https://image.noelshack.com/fichiers/2019/44/4/1572547803-closed.png
When open: https://image.noelshack.com/fichiers/2019/44/4/1572547810-open-outside.png
When open and traveling throught: https://image.noelshack.com/fichiers/2019/44/4/1572547806-open-inside.png

**Comment by Wyn-Price** [comment]
Can you send the latest.log? Do you have optifine installed

**Comment by ExDomino** [comment]
I do have optifine installed.
You need the "latest.log" after I open and closed the door then closed my game?

**Comment by ExDomino** [comment]
I open the game;
I connected to my server;
I open the door, closed the door, passed throught it and closed it again;
I disconnected from my server;
I closed the game;
Then I retrieved the "latest.log" file and sent it to you.

https://pastebin.com/50sn6Mt6

**Comment by Wyn-Price** [comment]
Oh this is 1.12, i didn't see that. 1.12 is very broken at the moment, and i do plan on porting the current system to 1.12

**Comment by ExDomino** [comment]
It is indicated on my very first post.

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
