### ISSUE TITLE
[1.14.4] Secret player pressure plates do not activate adjacent doors.

### ISSUE THREAD

**Issue by fuzzyweapon** [Wyn-Price/SecretRooms#11]
Secret Rooms - 6.0.4
MC - 1.14.4
Forge - 28.1.56

Normally when pressure plates are adjacent to door blocks, the player can walk over them and it will activate an adjacent door.

For the Secret player pressure plates, if I put one on either side of the block that the door is placed on, neither secret player pressure plate works.

The only way to get it to work at all is to make the block the door is placed on the secret pressure plate.  The problem with this is then the pressure plate can work for moving through one side of the door (the side that exposes the block), but not going through the other.

This is either flawed design or a bug when secret pressure plates are placed in the expected spot.

**Comment by Wyn-Price** [comment]
Theoretically, placing secret redstone under the door should work, although I do understand currently secret redstone is broken.

**Comment by fuzzyweapon** [comment]
It does from one way, but not the other way bc of the physical design of doors...so, it kinda makes them not very useful except for niche purposes.  Does that make sense?  So you're right, functionally they are working as designed.

**Comment by fuzzyweapon** [comment]
Closing this as by design (and all good!).  Confirmed that the Secret Redstone fixes made it possible for me to place the secret pressure plates anywhere and us Secret Redstone to carry the signal to the door for both sides.
