### ISSUE TITLE
[1.14.4] Secret Redstone does not toggle back to off state after being activated with Secret Lever.

### ISSUE THREAD

**Issue by fuzzyweapon** [Wyn-Price/SecretRooms#12]
MC - 1.14.4
Forge - 28.1.56
Secret Doors - 6.0.4

----

Put down redstone (for visibility of bug), then secret redstone (I did a line of two), then secret lever.

Activate the secret lever, observe redstone is activated.
De-activate the secret lever, observe redstone is still activated.

**Comment by fuzzyweapon** [comment]
Looks like this happens with the Secret Lever and the Torch Lever.  You just need to have more than one Secret Redstone block in a row (this was reproduced with the same **kind** of Secret Redstone block, aka stone-stone, so contiguous or discontiguous, aka stone-wood planks, does not matter).

**Comment by fuzzyweapon** [comment]
This also affects the vanilla lever.  So this is a bug with Secret Redstone.

**Comment by Wyn-Price** [comment]
~~Could you post a picture of your setup? Just to make testing easier~~
Just noticed the other issue.

**Comment by Wyn-Price** [comment]
The issue actually occurs when you place the vanilla redstone. The vanilla redstone is getting powered with strong power from the secret redstone one after the secret redstone connecting to it. For example:
![image](https://user-images.githubusercontent.com/15876682/67982112-f8333c00-fc19-11e9-8df7-dce497fa9c9c.png)
Will not cause issues as the only block that can power the vanilla redstone is `B`, but in:
![image](https://user-images.githubusercontent.com/15876682/67982183-15680a80-fc1a-11e9-94a6-c4bbd1b960df.png)
Block A can power the redstone wire through block B, in the same way a repeater can power a block through another block. In this senario, it's not an issue, as the redstone level in block `A` will be less than in block `B`, but in:
![image](https://user-images.githubusercontent.com/15876682/67982342-6f68d000-fc1a-11e9-9e52-5c7d0b7c76fd.png)
That is not the case, and the signal strength in A will be larger than the strength in B. This means that the redstone wire strength is larger than the strength in B, thus it's the redstone wire poweres B, which then poweres the redstone wire, hence nothing gets unpowered.
This is just an oversite in my part.
