### ISSUE TITLE
Secret Redstone Block output state

### ISSUE THREAD

**Issue by Anuuviem** [Wyn-Price/SecretRooms#18]
MC 1.14.4
Forge X.1.90

When a secret redstone block receives input signal, functions right, after signal is terminated, block does not shut off.

**Comment by Wyn-Price** [comment]
What version of secret rooms is this? This sounds like a duplicate of #12

**Comment by Anuuviem** [comment]
Sorry for the late reply: secretrooms-6.0.5

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
