### ISSUE TITLE
Game Freeze w/ MC Paint

### ISSUE THREAD

**Issue by WenXin20** [Wyn-Price/SecretRooms#19]
`Minecraft v1.14.4`
`Forge v28.1.90`
`Secret Rooms v6.0.5`
[`MC Paint v1.4.5`](https://www.curseforge.com/minecraft/mc-mods/mc-paint)

The game froze after I accidentally placed a camouflage block next to a block that had been painted on using the mod MC Paint. If you look at `[01:49:53]`, you can see the error.
[Log](https://gist.github.com/WenXin20/7878443dd2d1464592bb11126af53639)

**Comment by Wyn-Price** [comment]
The log only goes up to `[01:19:20]` maybe try pasting only the last part of the log, with the error, seeing as I've gotten the first half.

**Comment by WenXin20** [comment]
[Here ](https://gist.github.com/WenXin20/e9ce730d1043ca8297e249ea93776412)it is

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
