### ISSUE TITLE
Bug report or glitch idk

### ISSUE THREAD

**Issue by SimonAI-cpu** [Wyn-Price/SecretRooms#21]
any block i place, ANY block, becomes solid stone block, im on single player, no texture pack on.
![2019-12-13_22 07 27](https://user-images.githubusercontent.com/58703090/70828935-1bdeca00-1df5-11ea-8de3-30cb508f75d6.png)
![Uploading 2019-12-13_22.07.41.png…]()
![Uploading 2019-12-13_22.07.48.png…]()
![Uploading 2019-12-13_22.08.07.png…]()

**Comment by Josh65-2201** [comment]
Optifine can cause this issue. This version works but waila does not work with blocks metadata like concrete and wool colours if you are also using that mod.
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2537890

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
