### ISSUE TITLE
Interacting with Secret Iron Door causes crash for all users

### ISSUE THREAD

**Issue by bradsk88** [Wyn-Price/SecretRooms#23]
I placed a secret iron door upon a Quartz Glass block, surrounded by chiseled vanilla glass blocks.

This error also occurred after placing the door on vanilla oak wood planks.  The crash happened when I tried to destroy the door.

[mclog.txt](https://github.com/Wyn-Price/SecretRooms/files/4004300/mclog.txt)

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
