### ISSUE TITLE
The mod only sets blocks as stone and won’t change to other blocks

### ISSUE THREAD

**Issue by dog10109** [Wyn-Price/SecretRooms#25]

**Comment by McfarlaneRob** [comment]
i have the same problem.
I can place a secret door completely surrounded by stone bricks and "The one probe" will tell me that i  am looking at stone bricks when looking at the door, but the texture is always for smooth stone.

**Comment by Josh65-2201** [comment]
Optifine can cause this issue. This version works but waila does not work with blocks metadata like concrete and wool colours if you are also using that mod.
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2537890

**Comment by dog10109** [comment]
What do you mean by waila?

**Comment by Josh65-2201** [comment]
It's another mod that tells you what your looking at in game.

**Comment by TheBoiPotato** [comment]
If you install an older version of optifine, the blocks will change, and you won't see stone anymore.

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
