### ISSUE TITLE
I see only stone

### ISSUE THREAD

**Issue by pjindras** [Wyn-Price/SecretRooms#27]
Hello in lastest version on 1.12.2 when i use something ex. door i see it only like a stone, it dont take the camouflage of the block standing downstairs its just always only stone.

**Comment by josh-65** [comment]
Optifine can cause this issue. I also dont think its ever going to be fixed.

**Comment by josh-65** [comment]
Ths one seems to work but waila does not with it.
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2537890

**Comment by Josh65-2201** [comment]
Optifine can cause this issue. This version works but waila does not work with blocks metadata like concrete and wool colours if you are also using that mod.
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2537890

**Comment by fkrisi11** [comment]
Same here. I do have optifine though. But a fix would be nice if it was possible
1.12.2, version secretroomsmod-1.12.2-5.6.4

**Comment by TheBoiPotato** [comment]
Just install an older version of optifine and the blocks will go back to normal/will camouflage.

**Comment by Wyn-Price** [comment]
1.12 is no longer supported sorry
