### ISSUE TITLE
[1.14.4] Server crash on load on Dedicated server- Sidedness issue?

### ISSUE THREAD

**Issue by ProsperCraft** [Wyn-Price/SecretRooms#3]
Secret Rooms 6 (secretroomsmod) has failed to load correctly
§7net/minecraft/client/gui/FontRenderer

Console-
https://gist.github.com/ProsperCraft/25ab690c3f392c976a96216ad3bc11e5

Crash-
https://gist.github.com/ProsperCraft/adc712e994ce15e9b0e49325f7780865

Logs-
[secretrooms.zip](https://github.com/Wyn-Price/SecretRooms/files/3694612/secretrooms.zip)

**Comment by Wyn-Price** [comment]
Should be fixed in [6.0.1](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2803267)
