### ISSUE TITLE
I see only stone

### ISSUE THREAD

**Issue by HellZone000** [Wyn-Price/SecretRooms#30]
when i place a block it doesn't camo but it remain stone, **HELP PLSSSS** :'((((((

**Comment by Acoorn** [comment]
Secretrooms only works without optifine for some reason. I think it has something to do with the way forge and optifine work together. You might need to uninstall optifine or you can try switching to a different older version of forge. I hope this helps ^v^

**Comment by darthvader45** [comment]
Weird. I don't even have Optifine installed.  I'll check to see if having a leftover optionof.txt does the same thing as having Optifine installed.

**Comment by TheBoiPotato** [comment]
All you have to do is install an older version of Optifine

**Comment by Wyn-Price** [comment]
1.12 is no longer supported
