### ISSUE TITLE
[1.12.2] Issue with CTM chisel blocks

### ISSUE THREAD

**Issue by brisingraerowing** [Wyn-Price/SecretRooms#32]
A picture is worth a thousand words, so...
![2020-06-06_13 56 49](https://user-images.githubusercontent.com/250409/83951187-c14f8500-a7fd-11ea-8424-6dc99a33867c.png)

The block to the left is what they should look like. The doors are Secret Iron Doors.

**Comment by Acoorn** [comment]
It most likely has to do with the way it renders the block. Try wooden doors or simply a piston door made of the blocks instead. Optifine is really buggy with it, so if you have optifine, it might not work. If you want to keep iron doors, you may have to tinker with the textures. It's most likely that it isnt made to be compatible with all blocks from mods. Sorry if this doesnt help, but hope it does.

**Comment by Wyn-Price** [comment]
1.12 is no longer supported.
