### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by WenXin20** [Wyn-Price/SecretRooms#43]
`Minecraft v1.16.5`
`Forge v36.0.46`
`Secret Rooms v1.16.4`

- Both doors drop 3 when broken and do not have collision.
- The wooden secret door and gate can't be opened with a right-click.
- Doors and trapdoors have squished textures on their sides.
- Doors and trapdoors always face the same direction.
- The chest gui is missing localization.
- All blocks break instantly.
- The secret stairs does not work like stairs and has a full collision box.
- The wall torch lever is missing a loot table and has collision.
- The torch lever renders incorrectly, has blue flames and has collision. (Seen below)

(The door on the left is open using a secret lever, the other is closed.)
![2021-03-05_22 54 25](https://user-images.githubusercontent.com/12000593/110195846-d34e6a80-7e05-11eb-9c8f-311289297ac4.png)

**Comment by Romaindu35** [comment]
Hello, thank you for your bug report, I will try to fix bugs, on the other hand there is a bug that I do not understand: "The chest gui is missing localization". Can you explain it to me a little better or even show me a picture ?

**Comment by WenXin20** [comment]
No problem. :)

For the chest gui, where it would normally say "chest" in the top left corner of the gui, it instead has an unlocalized string because it is missing from the en_us lang file.

**Comment by WenXin20** [comment]
![2021-03-08_16 30 47](https://user-images.githubusercontent.com/12000593/110390581-d460e100-802b-11eb-92b7-68bc95836a53.png)

**Comment by WenXin20** [comment]
Could waterlogging also be added? The secret blocks can copy waterlogged stairs, etc, but the secret block won't become waterlogged.

**Comment by Romaindu35** [comment]
ok, thank you I understand the bug better (In fact I had already fixed this bug: coming in the next update) By cons I do not understand the system with waterlogging

**Comment by WenXin20** [comment]
Nice! Which part of waterlogging?

**Comment by Romaindu35** [comment]
All, I don't understand what you want me to add?

**Comment by WenXin20** [comment]
So that when a secret block is placed underwater, it becomes waterlogged, because it currently won't.

**Comment by Romaindu35** [comment]
ok
