### ISSUE TITLE
[1.16.5] Jade (waila fork) displays name of block instead of fake name

### ISSUE THREAD

**Issue by EnderMelody** [Wyn-Price/SecretRooms#45]
Not sure if this is a problem with other waila forks, but Jade shows the actual name of the secret block instead of the block it is mimicking.
![2021-03-13_11 24 39](https://user-images.githubusercontent.com/12649140/111039048-0098ab00-83fa-11eb-8352-8e00caa82b6a.png)

**Comment by OakBricks-old** [comment]
![image](https://user-images.githubusercontent.com/65257189/111860171-c193b980-8913-11eb-8bce-69a1c8a758af.png)
Not just a WAILA/HWYLA fork issue, the same issue happens with The One Probe

**Comment by EnderMelody** [comment]
So its not secretroomsmods end not the name displayer, will close.
