### ISSUE TITLE
[1.12.2] 2 bugs

### ISSUE THREAD

**Issue by ZeltigDemon** [Wyn-Price/SecretRooms#5]
1)  I Placed the One Way Glass behind Light source out of Simply Light and the game crash and is 
     broken now, game crashes when loading the save game. 
2)  Placeing the one way glass on top of basalt (i used one out of chisel) can/will make it Invisible

**Comment by Wyn-Price** [comment]
I need the crashlog before I can do anything

**Comment by ZeltigDemon** [comment]
[crash-2019-10-09_23.36.51-client.txt](https://github.com/Wyn-Price/SecretRooms/files/3714392/crash-2019-10-09_23.36.51-client.txt)

**Comment by Wyn-Price** [comment]
1.12 is no longer supported.
