### ISSUE TITLE
Server Crash forge:36.1.32

### ISSUE THREAD

**Issue by HonestAngel** [Wyn-Price/SecretRooms#50]
Details:
	Mod File: secretrooms-1.16.5-1.1.1.jar
	Failure message: Secret Rooms 6 (secretroomsmod) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
	Mod Version: 1.16.5-1.1.1
	Mod Issue URL: NOT PROVIDED
[crash-2021-07-02_08.39.37-fml.txt](https://github.com/Wyn-Price/SecretRooms/files/6753317/crash-2021-07-02_08.39.37-fml.txt)

**Comment by HonestAngel** [comment]
I took out optifine and it still crashed with the same reason.
[crash-2021-07-02_08.50.19-fml.txt](https://github.com/Wyn-Price/SecretRooms/files/6753346/crash-2021-07-02_08.50.19-fml.txt)

**Comment by Wyn-Price** [comment]
Fixed with d72fa19fb912def825d35083f2f2a336c0d777be
