### ISSUE TITLE
1.14.4 - Secret Restone doesn't work

### ISSUE THREAD

**Issue by UncleSam139** [Wyn-Price/SecretRooms#6]
The Secret Redstone doesn't work if you let it go around a corner or from a higher block to a lower block. Tested it with normal redstone and then it works, but that's not the target of the mod.

**Comment by UncleSam139** [comment]
Found out, that the Secret Redstone is not compatible with normal Redstone.

**Comment by Wyn-Price** [comment]
Secret redstone isn't like normal redstone. It can't go up and down hills like normal redstone. It acts as a "tube", only supplying a redstone signal to the blocks directly around it (up, down, north, east, south, west)

**Comment by fuzzyweapon** [comment]
I think something actually might be broken here even according to what you've said @Wyn-Price 
...

In my following examples, I have marked each secret redstone block with a red slash and the torch is an activated (emitting redstone signal) secret torch lever.

The following works as indicated by the redstone receiving the signal...

![image](https://user-images.githubusercontent.com/1253399/67915027-d1183400-fb5f-11e9-85da-274301713111.png)

Now the following does not, even though according to what you've said this should be piping out signal to all directions and it is all on the same plane...

![image](https://user-images.githubusercontent.com/1253399/67915181-3a984280-fb60-11e9-9acd-566745a9345b.png)

**Comment by fuzzyweapon** [comment]
It looks like as soon as you try to change directions using the secret redstone blocks **as pipes**, they don't carry the signal further.

Yet I can do this:

![image](https://user-images.githubusercontent.com/1253399/67915332-aa0e3200-fb60-11e9-9569-9d269861b7c9.png)

and then this:

![image](https://user-images.githubusercontent.com/1253399/67915390-d3c75900-fb60-11e9-8f2c-4d8790b10a92.png)

So, according to the _logic_ of the mod, if it is supposed to be carrying signal between secret redstone blocks in all directions like a pipe, there is a bug.  Intuitively, the player would expect this to work if they can pipe secret redstone blocks three in a row on the same plane.

**Comment by fuzzyweapon** [comment]
What the actual bug looks like is that secret redstone blocks can send redstone signals in all directions, but not receive them.

**Comment by fuzzyweapon** [comment]
I've seen some strange stuff happening with redstone, and if I get a repro, I will stick in another bug...but I've even seen the signal not carrying but one block off the secret redstone block...or then altogether not picking up the signal from a secret lever even though the lever has been left in the activated state the entire time.  I'm only mentioning this briefly here in case it might not be easy to repro this as it might be related.
