### ISSUE TITLE
1.12.2: Everything I mean everything is stone!

### ISSUE THREAD

**Issue by MrClumsyboi** [Wyn-Price/SecretRooms#66]
Hi I installed Secretrooms mod I have the recommended 1.12.2 forge installer I have optifine 1.12.2 G5 and I installed the most downloaded version of secretrooms from curseforge which 2m+ downloads on the 1st 1.12.2 version you see and I load up and everything item related to the mod is stone. I don't even have texture packs! PLS HELP

**Comment by Wyn-Price** [comment]
1.12.2 + latest optifine is not supported
