### ISSUE TITLE
[1.14.4] Weird shift click behavior with mouse tweaks

### ISSUE THREAD

**Issue by gabriel-andreescu** [Wyn-Price/SecretRooms#7]
Problem: shift clicking multiple items on the same type don't combine them into one stack, instead 2 or more stacks are created, when you click one of them, it combines them as if it was a visual glitch

How to recreate: new sp world, get some wood, split it into your inv, then shift click DRAG over the splited items so they go into your hotbar

[Issue on Mouse Tweaks tracker](https://github.com/YaLTeR/MouseTweaks/issues/27)

MouseTweaks-2.12-mc1.14.4.jar
secretrooms-6.0.1.jar
forge 28.1.39

**Comment by Wyn-Price** [comment]
I really don't think this is a secretrooms issue. Remove secret rooms and see if it persists.

**Comment by gabriel-andreescu** [comment]
If you check the issues page over at Mouse Tweaks, I did tested with only Mouse Tweaks, and there's no issue.

**Comment by Wyn-Price** [comment]
Update to the latest forge and see if it still happens. There is literally no reason that secret rooms would cause this, I don't mess with anything inventory related.

**Comment by Wyn-Price** [comment]
Also could you send a video / gif of the issue in action

**Comment by gabriel-andreescu** [comment]
Look, I'm just trying to help here :) , it's literally two mods, not very hard to check it out for yourself.
I've updated to latest forge, still happens.

![2019-10-13 18-52](https://user-images.githubusercontent.com/3175443/66718269-a81b4380-edea-11e9-9ec7-e6b3acdf30f7.gif)

**Comment by Wyn-Price** [comment]
Unable to reproduce. Try resetting your mouse tweaks config if you haven't already.
![javaw_WW9XdMsRpi](https://user-images.githubusercontent.com/15876682/66718418-9f6f4100-eddb-11e9-8869-b268a2ad127e.png)
![w2KQOhebj6](https://user-images.githubusercontent.com/15876682/66718419-a6964f00-eddb-11e9-99b8-47046bc6eb64.gif)
