### ISSUE TITLE
[1.16] Secret redstone incorrect culling

### ISSUE THREAD

**Issue by devjavu7** [Wyn-Price/SecretRooms#73]
When putting a secret redstone imitating a fence on top of a full block, the full block will cull incorrectly.
After further testing I could also identify imitating fence gates, walls and anvils to cause the same issue. This is also not only an issue with secret redstone but the following: secret redstone, secret chest, secret trapped chest, secret stone button, secret wooden button, secret lever, secret pressure plate, secret player pressure plate, secret stairs, secret dummy block, secret gate, secret observer.
![2022-03-23_16 26 06](https://user-images.githubusercontent.com/88561769/159736073-ad0903fa-2612-43bf-8127-c12905e68b5a.png)
![2022-03-23_16 26 19](https://user-images.githubusercontent.com/88561769/159736087-50c2b835-a3e7-4296-81de-30711d2c03f2.png)

**Comment by embeddedt** [comment]
I can't reproduce this. I tried building a setup almost identical to that in the screenshot and it worked fine. Does it occur with only Secret Rooms installed? If so, can you provide a world file with a setup that demonstrates the issue?

EDIT: Nevermind, it's reproduced after walking away and coming back.

**Comment by embeddedt** [comment]
I think it might be a deeper issue with the way the blockstate is handled when a chunk is reloaded. After flying away from the fence and back in creative, its position has a light level of 0, causing an ugly black spot and incorrect lighting.

**Comment by devjavu7** [comment]
I have been thinking a little bit about this and I could imagine that you could try to set the secret blocks to be transparent, which should force the face of the block underneath to be rendered.
