### ISSUE TITLE
Fabric Does Not Detect The Mod

### ISSUE THREAD

**Issue by NatickYT** [Wyn-Price/SecretRooms#76]
When Using The Mod, I Tried To Do What Was Stated On The Curseforge Page But It Didn't Work, It Is In The Mods Folder With Some Other Mods But The Mod Menu Did Not Detect It
![Minecraft_ 1 18 2 - Singleplayer 02_05_2022 15_54_29](https://user-images.githubusercontent.com/99545540/166255864-6132b46d-c5bd-4f8a-822d-c58a26d9e7af.png)

**Comment by Wyn-Price** [comment]
This is for the forge secret rooms mod.

**Comment by NatickYT** [comment]
Oh Yeah
