### ISSUE TITLE
curseforge doesn't display video, fyi

### ISSUE THREAD

**Issue by cobaltcoyote** [Wyn-Price/SecretRooms#77]
not exactly a mod issue, but this seemed the best way to let you know.

the video link is http, not https, and is blocked as mixed content. this means it will not show if using some very basic security settings - in edge you cannot even turn this off, so all that shows is a video-embed shaped blank space. had to open page source to find the link, since I wanted watch it.

**Comment by Wyn-Price** [comment]
Cheers
