### ISSUE TITLE
[Conflict] Smooth Entity Light + SecretRooms

### ISSUE THREAD

**Issue by Nydid-ForcedDev** [Wyn-Price/SecretRooms#8]
When this mod is added with the other mod, that mod will not work (won't generate light)
If more info is needed, do ask for more as I do not really know what I should add.. Sorry

**Comment by Wyn-Price** [comment]
Post the full `debug.log`. What is this "other mod"

**Comment by Nydid-ForcedDev** [comment]
https://www.curseforge.com/minecraft/mc-mods/smooth-entity-light , It's a mod that add's dynamic light to torches and such, I am planning on using it with Hardcore Darkness.

Debug.log : https://controlc.com/5f03f69b

**Comment by Wyn-Price** [comment]
1.12 is no longer supported.
