### ISSUE TITLE
[1.14.4] 6.0.3 crash on dedicated server

### ISSUE THREAD

**Issue by gabriel-andreescu** [Wyn-Price/SecretRooms#9]
Your last update is now causing a crash on dedi:

Attempted to load class net/minecraft/client/renderer/color/BlockColors for invalid dist DEDICATED_SERVER

crash-report:
[https://pastebin.com/raw/tEDjuKmX](https://pastebin.com/raw/tEDjuKmX)

**Comment by Wyn-Price** [comment]
https://www.curseforge.com/minecraft/mc-mods/secretroomsmod/files/2808889
